// Code generated by DataTableGen. DO NOT EDIT.

DT{{.TableName}} = {
     {{range .Rows}}
     [{{.Index}}] = { {{range .DataVar}} {{.VarName}} = {{.VarValue}},{{end}} },
    {{end}}
}

local _default = {
    {{range .DataVar}}
    {{.VarName}} = {{.VarValue}}, 
    {{end}}
}

local _base = {
    __index = function(tbl,key)
        return _default[key]
    end, 
    __newindex = function(tbl,key,value)
        Log.Error( "Attempt to modify read-only table DT{{.TableName}}: key:{0},value:{1}",key,value)
        rawset(tbl,key,value)
    end,
    __metatable = false,
}

local mt = setmetatable
for k, v in pairs( DT{{.TableName}} ) do
    mt( v, _base )
end